### PR TITLE
Changes to make work doctest and tests for lts-6

### PR DESCRIPTION
**Pull request by jneira**
currently building in appveyor: https://ci.appveyor.com/project/jneira/dhall-haskell/builds/26147457

### CODE REVIEW

**Comment by jneira** [comment]
`chcp 65001` didnt work, i think cause each line of the script is running in a new console session

**Comment by jneira** [comment]
Build succeded! :smile:

**Comment by jneira** [comment]
@quasicomputational maybe you would have preferred that changes had been proposed in a review in the original pr? let me know it it is the case

**Comment by quasicomputational** [comment]
Thanks! Makes sense to me to send a PR when the changes are even slightly substantive.

**Pull request merged**
